name: "ha-js-control"
description: "Write Home Assistant automations dynamically in JavaScript."
version: "1.0.0"
image: "ghcr.io/atraber/ha-js-control"
slug: "ha-js-control"
init: false
arch:
  - amd64
map:
  - config:rw
options:
  automations_dir: "/config/js-automations"
schema:
  automations_dir: "str"
host_network: true
